[2025-07-08T00:00:24.263+0000] {processor.py:161} INFO - Started process (PID=56329) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:00:24.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:00:24.266+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:00:24.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:00:24.272+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:00:24.271+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:00:24.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:00:24.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.028 seconds
[2025-07-08T00:00:54.572+0000] {processor.py:161} INFO - Started process (PID=56365) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:00:54.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:00:54.573+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:00:54.573+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:00:54.578+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:00:54.577+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:00:54.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:00:54.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.020 seconds
[2025-07-08T00:01:24.924+0000] {processor.py:161} INFO - Started process (PID=56394) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:01:24.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:01:24.927+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:01:24.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:01:24.934+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:01:24.932+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:01:24.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:01:24.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.030 seconds
[2025-07-08T00:01:55.255+0000] {processor.py:161} INFO - Started process (PID=56430) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:01:55.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:01:55.256+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:01:55.256+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:01:55.260+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:01:55.260+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:01:55.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:01:55.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.020 seconds
[2025-07-08T00:02:25.584+0000] {processor.py:161} INFO - Started process (PID=56467) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:02:25.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:02:25.587+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:02:25.586+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:02:25.592+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:02:25.592+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:02:25.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:02:25.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.030 seconds
[2025-07-08T00:02:55.952+0000] {processor.py:161} INFO - Started process (PID=56503) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:02:55.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:02:55.954+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:02:55.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:02:55.960+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:02:55.960+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:02:55.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:02:55.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.026 seconds
[2025-07-08T00:03:26.313+0000] {processor.py:161} INFO - Started process (PID=56532) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:03:26.314+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:03:26.315+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:03:26.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:03:26.320+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:03:26.319+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:03:26.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:03:26.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.025 seconds
[2025-07-08T00:03:56.691+0000] {processor.py:161} INFO - Started process (PID=56568) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:03:56.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:03:56.694+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:03:56.694+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:03:56.701+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:03:56.701+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:03:56.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:03:56.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.029 seconds
[2025-07-08T00:04:27.000+0000] {processor.py:161} INFO - Started process (PID=56604) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:04:27.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:04:27.001+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:04:27.001+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:04:27.007+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:04:27.006+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:04:27.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:04:27.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.021 seconds
[2025-07-08T00:04:57.353+0000] {processor.py:161} INFO - Started process (PID=56640) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:04:57.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:04:57.355+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:04:57.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:04:57.360+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:04:57.360+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:04:57.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:04:57.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.024 seconds
[2025-07-08T00:05:27.697+0000] {processor.py:161} INFO - Started process (PID=56676) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:05:27.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:05:27.699+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:05:27.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:05:27.702+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:05:27.702+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:05:27.702+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:05:27.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.023 seconds
[2025-07-08T00:05:58.068+0000] {processor.py:161} INFO - Started process (PID=56705) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:05:58.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:05:58.069+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:05:58.069+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:05:58.074+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:05:58.074+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:05:58.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:05:58.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.023 seconds
[2025-07-08T00:06:28.343+0000] {processor.py:161} INFO - Started process (PID=56740) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:06:28.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:06:28.344+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:06:28.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:06:28.350+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:06:28.349+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:06:28.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:06:28.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.025 seconds
[2025-07-08T00:06:58.687+0000] {processor.py:161} INFO - Started process (PID=56776) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:06:58.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:06:58.688+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:06:58.688+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:06:58.694+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:06:58.693+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:06:58.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:06:58.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.024 seconds
[2025-07-08T00:07:29.030+0000] {processor.py:161} INFO - Started process (PID=56812) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:07:29.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:07:29.033+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:07:29.032+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:07:29.038+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:07:29.037+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:07:29.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:07:29.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.028 seconds
[2025-07-08T00:07:59.401+0000] {processor.py:161} INFO - Started process (PID=56847) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:07:59.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:07:59.402+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:07:59.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:07:59.406+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:07:59.406+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:07:59.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:07:59.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.020 seconds
[2025-07-08T00:08:29.678+0000] {processor.py:161} INFO - Started process (PID=56877) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:08:29.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:08:29.679+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:08:29.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:08:29.683+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:08:29.683+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:08:29.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:08:29.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.018 seconds
[2025-07-08T00:08:59.943+0000] {processor.py:161} INFO - Started process (PID=56913) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:08:59.944+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:08:59.945+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:08:59.945+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:08:59.948+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:08:59.948+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:08:59.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:08:59.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.018 seconds
[2025-07-08T00:09:30.171+0000] {processor.py:161} INFO - Started process (PID=56949) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:09:30.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:09:30.172+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:09:30.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:09:30.177+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:09:30.177+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:09:30.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:09:30.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.022 seconds
[2025-07-08T00:10:00.424+0000] {processor.py:161} INFO - Started process (PID=56985) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:10:00.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:10:00.425+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:10:00.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:10:00.430+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:10:00.429+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:10:00.431+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:10:00.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.023 seconds
[2025-07-08T00:10:30.687+0000] {processor.py:161} INFO - Started process (PID=57014) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:10:30.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:10:30.688+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:10:30.688+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:10:30.692+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:10:30.692+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:10:30.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:10:30.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.022 seconds
[2025-07-08T00:11:01.013+0000] {processor.py:161} INFO - Started process (PID=57049) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:11:01.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:11:01.015+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:11:01.015+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:11:01.018+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:11:01.018+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:11:01.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:11:01.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.023 seconds
[2025-07-08T00:11:31.400+0000] {processor.py:161} INFO - Started process (PID=57085) to work on /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:11:31.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_with_docker.py for tasks to queue
[2025-07-08T00:11:31.403+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:11:31.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:11:31.409+0000] {logging_mixin.py:188} INFO - [2025-07-08T00:11:31.409+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_with_docker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_with_docker.py", line 143
    trainer = Trainer(
                     ^
SyntaxError: '(' was never closed
[2025-07-08T00:11:31.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_with_docker.py
[2025-07-08T00:11:31.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_with_docker.py took 0.030 seconds
